apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: YWJj
  MYSQL_PASSWORD: YWFhMTIz

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    version: "8.0.32"
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.32
    envFrom:
    - secretRef:
        name: mysql-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
data:
  WORDPRESS_DB_HOST: bXlzcWwtc3Zj
  WORDPRESS_DB_USER: YWJj
  WORDPRESS_DB_PASSWORD: YWFhMTIz
  WORDPRESS_DB_NAME: d29yZHByZXNz
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    version: "6.2.0"
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:6.2.0
    envFrom:
    - secretRef:
        name: wordpress-secret

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30000
      #type: LoadBalancer
  type: ClusterIP

---

#kubectl create configmap nginx-cfg --from-file=./nginx.conf

---

#kubectl create configmap fluentd-cfg --from-file=./fluent.conf

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.23.4
      volumeMounts:
        - mountPath: "/etc/nginx"
          name: nginx-cfg
        - mountPath: /var/log/nginx
          name: log-volume

    - name: fluentd
      image: fluentd:v1.16-1
      volumeMounts:
        - mountPath: "/fluentd/etc"
          name: fluentd-cfg
        - mountPath: /logs
          name: log-volume

  volumes:
    - name: log-volume
      emptyDir: {}
    - name: nginx-cfg
      configMap:
        name: nginx-cfg
        defaultMode: 0400
    - name: fluentd-cfg
      configMap:
        name: fluentd-cfg
        #defaultMode: 0400
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: LoadBalancer